server:
  port: 8081
spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guoli?serverTimezone=GMT%2B8
    username: root
    password: guoyibin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
mybatis-plus:
  mapper-locations: classpath:com/guo/serviceedu/mapper/xml/*.xml
feign:
  hystrix:
    enabled: true
